name: Tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        goversion: [1.16, 1.15, 1.14, 1.13]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.goversion }}
    - name: Install dependencies
      run: |
          sudo snap install core core18
          sudo snap install --edge tpm2-simulator-chrisccoulson
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cache Go dependencies
      id: cache-go-modules
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Build
      run: go build -v -mod=readonly ./...
    - name: Test
      run: go test -v -race -p 1 -mod=readonly ./... -args -use-mssim
    - name: Go vet
      run: go vet ./...
